(in-package #:vimcl)

(defun normalize-key (key)
  "Map a charms key to a keyword or (list :char CH)."
  (if (characterp key)
      (case key
        (#\Escape :escape)
        (#\Newline :enter)
        (#\Return :enter)
        (#\Del :backspace)
        (#\Rubout :backspace)
        (t (list :char key)))
      (case key
        (27 :escape)
        (13 :enter)
        (10 :enter)
        (127 :backspace)
        (263 :backspace)
        (260 :left)
        (261 :right)
        (259 :up)
        (258 :down)
        (t nil))))

(defun editor-key-insert (buf key)
  (let ((norm (normalize-key key)))
    (cond
      ((eq norm :escape) (values buf :normal nil))
      ((eq norm :enter) (values (buffer-split-line buf) :insert nil))
      ((eq norm :backspace) (values (buffer-delete-backward buf) :insert nil))
      ((and (consp norm) (eq (first norm) :char))
       (values (buffer-insert-char buf (second norm)) :insert nil))
      (t (values buf :insert nil)))))

(defun editor-key-normal (buf key)
  (let ((norm (normalize-key key)))
    (if (and (consp norm) (eq (first norm) :char))
        (let ((ch (second norm)))
          (case ch
            (#\h (values (buffer-move buf 0 -1) :normal nil))
            (#\j (values (buffer-move buf 1 0) :normal nil))
            (#\k (values (buffer-move buf -1 0) :normal nil))
            (#\l (values (buffer-move buf 0 1) :normal nil))
            (#\0 (values (buffer-move buf 0 (- (buffer-col buf))) :normal nil))
            (#\$ (values (buffer-move buf 0 9999) :normal nil))
            (#\x (values (buffer-delete-char buf) :normal nil))
            (#\i (values buf :insert nil))
            (#\a (values (buffer-move buf 0 1) :insert nil))
            (#\A (values (buffer-move buf 0 9999) :insert nil))
            (#\I (values (buffer-move buf 0 (- (buffer-col buf))) :insert nil))
            (#\o (values (buffer-open-line-below buf) :insert nil))
            (#\O (values (buffer-open-line-above buf) :insert nil))
            (#\G (values (buffer-move buf 9999 0) :normal nil))
            (t (values buf :normal
                       (format nil "Unknown: ~c" ch))))))
        (case norm
          (:left (values (buffer-move buf 0 -1) :normal nil))
          (:right (values (buffer-move buf 0 1) :normal nil))
          (:up (values (buffer-move buf -1 0) :normal nil))
          (:down (values (buffer-move buf 1 0) :normal nil))
          (:escape (values buf :normal nil))
          (:enter (values (buffer-split-line buf) :normal nil))
          (:backspace (values (buffer-delete-backward buf) :normal nil))
          (t (values buf :normal nil)))))

(defun editor-key (buf mode key)
  (case mode
    (:insert (editor-key-insert buf key))
    (t (editor-key-normal buf key))))
