(in-package #:vimcl)

(defun normalize-key (key)
  "Map a charms key to a keyword or (list :char CH)."
  (if (characterp key)
      (case key
        (#\Escape :escape)
        (#\Newline :enter)
        (#\Return :enter)
        (#\Del :backspace)
        (#\Rubout :backspace)
        (t (list :char key)))
      (case key
        (27 :escape)
        (13 :enter)
        (10 :enter)
        (127 :backspace)
        (263 :backspace)
        (260 :left)
        (261 :right)
        (259 :up)
        (258 :down)
        (t nil))))

(defun editor-key-insert (buf key)
  (let ((norm (normalize-key key)))
    (cond
      ((eq norm :escape) (values buf :normal nil))
      ((eq norm :enter) (values (buffer-split-line buf) :insert nil))
      ((eq norm :backspace) (values (buffer-delete-backward buf) :insert nil))
      ((and (consp norm) (eq (first norm) :char))
       (values (buffer-insert-char buf (second norm)) :insert nil))
      (t (values buf :insert nil)))))

(defun editor-key-normal (buf key)
  (let ((norm (normalize-key key))
        (ch (if (and (consp norm) (eq (first norm) :char))
                (second norm) nil)))
    (cond
      ((and ch (eql ch #\h)) (values (buffer-move buf 0 -1) :normal nil))
      ((and ch (eql ch #\j)) (values (buffer-move buf 1 0) :normal nil))
      ((and ch (eql ch #\k)) (values (buffer-move buf -1 0) :normal nil))
      ((and ch (eql ch #\l)) (values (buffer-move buf 0 1) :normal nil))
      ((and ch (eql ch #\0)) (values (buffer-move buf 0 (- (buffer-col buf))) :normal nil))
      ((and ch (eql ch #\$)) (values (buffer-move buf 0 9999) :normal nil))
      ((and ch (eql ch #\x)) (values (buffer-delete-char buf) :normal nil))
      ((and ch (eql ch #\i)) (values buf :insert nil))
      ((and ch (eql ch #\a)) (values (buffer-move buf 0 1) :insert nil))
      ((and ch (eql ch #\A)) (values (buffer-move buf 0 9999) :insert nil))
      ((and ch (eql ch #\I)) (values (buffer-move buf 0 (- (buffer-col buf))) :insert nil))
      ((and ch (eql ch #\o)) (values (buffer-open-line-below buf) :insert nil))
      ((and ch (eql ch #\O)) (values (buffer-open-line-above buf) :insert nil))
      ((and ch (eql ch #\G)) (values (buffer-move buf 9999 0) :normal nil))
      ((eq norm :left) (values (buffer-move buf 0 -1) :normal nil))
      ((eq norm :right) (values (buffer-move buf 0 1) :normal nil))
      ((eq norm :up) (values (buffer-move buf -1 0) :normal nil))
      ((eq norm :down) (values (buffer-move buf 1 0) :normal nil))
      ((eq norm :escape) (values buf :normal nil))
      ((eq norm :enter) (values (buffer-split-line buf) :normal nil))
      ((eq norm :backspace) (values (buffer-delete-backward buf) :normal nil))
      (t (values buf :normal nil)))))


(defun editor-key (buf mode key)
  (case mode
    (:insert (editor-key-insert buf key))
    (t (editor-key-normal buf key))))
